

---
- name: basic playbook
  user: ec2-user
  become: yes
  hosts: all
  tasks:
    - name: installing nginx
      yum:
        name: nginx
        state: present
    - name: starting nginx sever
      service:
        name: nginx
        state: started
        enabled: true
