
---

- name: dowload file to remote server
  hosts: all

  task:
    name: download file
    get_url: 
    url: https://www.python.org/downloads/release/python-3127/
    dest: /home/kajal/ansible/
    owner: kajal
    group: devops
    mode: u=rxw,g=r
    tags: fire
